"""Prediction heads.

* :class:`SegmentationHead` - final convolution producing the single-channel
  centerline logits for the proposed segmentation model (Equation 6).
* :class:`RTMDetInsHead` - the decoupled detection + dynamic-mask head of
  RTMDet-ins (Section 2.4, Equations 1-2): separate classification and box
  regression branches plus a kernel branch that conditions a dynamic
  convolution applied to shared mask prototype features.
"""

from __future__ import annotations

from typing import List, Sequence, Tuple

import torch
import torch.nn as nn

from .layers import ConvModule, init_weights


class SegmentationHead(nn.Module):
    """Final centerline prediction head.

    Produces raw logits; the sigmoid in Equation 6 is applied by the loss / the
    framework so that the head is compatible with mixed-precision training.

    Args:
        in_channels: Channels of the decoder output.
        num_classes: Number of output channels (1 for binary centerline).
        upsample_factor: Bilinear upsampling factor applied before the final conv.
    """

    def __init__(self, in_channels: int, num_classes: int = 1, upsample_factor: int = 1) -> None:
        super().__init__()
        layers: List[nn.Module] = []
        if upsample_factor > 1:
            layers.append(nn.UpsamplingBilinear2d(scale_factor=upsample_factor))
        layers.append(ConvModule(in_channels, in_channels, kernel_size=3, activation="relu"))
        layers.append(nn.Conv2d(in_channels, num_classes, kernel_size=1))
        self.head = nn.Sequential(*layers)
        init_weights(self)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Return raw centerline logits."""
        return self.head(x)


class MaskFeatModule(nn.Module):
    """Shared mask prototype branch for RTMDet-ins.

    Generates low-dimensional mask prototype features from the finest neck level.

    Args:
        in_channels: Channels of the neck feature used as input.
        feat_channels: Intermediate channel count.
        num_prototypes: Number of prototype channels emitted.
        stacked_convs: Number of stacked convolutions.
    """

    def __init__(
        self,
        in_channels: int,
        feat_channels: int = 64,
        num_prototypes: int = 8,
        stacked_convs: int = 4,
    ) -> None:
        super().__init__()
        convs: List[nn.Module] = []
        channels = in_channels
        for _ in range(stacked_convs):
            convs.append(ConvModule(channels, feat_channels, kernel_size=3, activation="silu"))
            channels = feat_channels
        self.stacked_convs = nn.Sequential(*convs)
        self.projection = nn.Conv2d(feat_channels, num_prototypes, kernel_size=1)
        self.num_prototypes = num_prototypes

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Return prototype features of shape ``(N, num_prototypes, H, W)``."""
        return self.projection(self.stacked_convs(x))


class RTMDetInsHead(nn.Module):
    """Decoupled RTMDet-ins head with a dynamic mask kernel branch.

    The head shares convolution stacks across pyramid levels and predicts, at
    every spatial location: class logits, distance-based bounding boxes and a
    vector of dynamic-convolution parameters (the *kernel*). A separate mask
    prototype branch produces shared features; instance masks are generated by
    convolving the prototypes (augmented with relative coordinates) with the
    per-instance dynamic kernels (Equation 2).

    Args:
        in_channels: Channels of every neck output level.
        num_classes: Number of object classes (1 = shrimp).
        feat_channels: Channel count of the shared convolution stacks.
        stacked_convs: Number of stacked convolutions per branch.
        num_prototypes: Number of mask prototype channels.
        dyconv_channels: Hidden channel count of the dynamic convolution.
        num_dyconvs: Number of dynamic convolution layers.
        num_levels: Number of pyramid levels.
    """

    def __init__(
        self,
        in_channels: int,
        num_classes: int = 1,
        feat_channels: int = 192,
        stacked_convs: int = 2,
        num_prototypes: int = 8,
        dyconv_channels: int = 8,
        num_dyconvs: int = 3,
        num_levels: int = 3,
    ) -> None:
        super().__init__()
        self.num_classes = num_classes
        self.num_prototypes = num_prototypes
        self.dyconv_channels = dyconv_channels
        self.num_dyconvs = num_dyconvs
        self.num_levels = num_levels

        self.cls_convs = self._make_stack(in_channels, feat_channels, stacked_convs)
        self.reg_convs = self._make_stack(in_channels, feat_channels, stacked_convs)

        self.cls_pred = nn.Conv2d(feat_channels, num_classes, kernel_size=3, padding=1)
        self.reg_pred = nn.Conv2d(feat_channels, 4, kernel_size=3, padding=1)

        # Number of generated parameters for the dynamic mask convolution.
        self.weight_nums, self.bias_nums = self._dynamic_param_shapes()
        num_gen_params = sum(self.weight_nums) + sum(self.bias_nums)
        self.kernel_pred = nn.Conv2d(feat_channels, num_gen_params, kernel_size=3, padding=1)

        # Learnable per-level scale for the distance regression outputs.
        self.scales = nn.ParameterList(
            [nn.Parameter(torch.ones(1)) for _ in range(num_levels)]
        )
        init_weights(self)
        # Bias init for classification (focal-loss friendly).
        nn.init.constant_(self.cls_pred.bias, -4.595)

    @staticmethod
    def _make_stack(in_channels: int, feat_channels: int, stacked_convs: int) -> nn.Sequential:
        convs: List[nn.Module] = []
        channels = in_channels
        for _ in range(stacked_convs):
            convs.append(ConvModule(channels, feat_channels, kernel_size=3, activation="silu"))
            channels = feat_channels
        return nn.Sequential(*convs)

    def _dynamic_param_shapes(self) -> Tuple[List[int], List[int]]:
        """Return the weight / bias element counts of every dynamic conv layer."""
        weight_nums: List[int] = []
        bias_nums: List[int] = []
        in_dim = self.num_prototypes + 2  # prototypes + relative xy coordinates
        for i in range(self.num_dyconvs):
            out_dim = self.dyconv_channels if i < self.num_dyconvs - 1 else 1
            weight_nums.append(in_dim * out_dim)
            bias_nums.append(out_dim)
            in_dim = out_dim
        return weight_nums, bias_nums

    def forward(
        self, feats: Sequence[torch.Tensor]
    ) -> Tuple[List[torch.Tensor], List[torch.Tensor], List[torch.Tensor]]:
        """Predict per-level classification, regression and kernel maps.

        Args:
            feats: Pyramid features from the neck (one tensor per level).

        Returns:
            A tuple ``(cls_scores, bbox_preds, kernel_preds)`` where each entry
            is a list with one tensor per pyramid level.
        """
        cls_scores: List[torch.Tensor] = []
        bbox_preds: List[torch.Tensor] = []
        kernel_preds: List[torch.Tensor] = []
        for level, feat in enumerate(feats):
            cls_feat = self.cls_convs(feat)
            reg_feat = self.reg_convs(feat)
            cls_scores.append(self.cls_pred(cls_feat))
            reg = self.reg_pred(reg_feat)
            bbox_preds.append(torch.relu(reg) * self.scales[level])
            kernel_preds.append(self.kernel_pred(reg_feat))
        return cls_scores, bbox_preds, kernel_preds
